baseURL = 'https://flipthebit.dev/'
locale = 'en-us'
title = 'Flip The Bit'
copyright = "flipthebit.dev (CC BY-NC-ND 4.0)"
theme = "PaperMod"
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
enableGitInfo = true

defaultContentLanguageInSubdir = false
DefaultContentLanguage = "en"

[params]
  comments = true
  mainSections = []
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = true
  ShareButtons = ["linkedin", "twitter", "reddit"]
  images = ["images/twitter_card.png"]
  [params.contact]
    email = "flipthebit@proton.me"

[markup]
[markup.highlight]
noClasses = false

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.sk]
    languageName = "Slovenčina"
    weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'
